"""Shared enums used across the domain model."""

import enum


class DataTruth(str, enum.Enum):
    """Classification of data provenance/truth."""
    REAL_DATA = "REAL_DATA"
    SYNTHETIC_DATA = "SYNTHETIC_DATA"
    MODEL_ESTIMATION = "MODEL_ESTIMATION"
    AI_GENERATED_TEXT = "AI_GENERATED_TEXT"
    EVIDENCE = "EVIDENCE"
    ASSUMPTION = "ASSUMPTION"
    HUMAN_INPUT = "HUMAN_INPUT"


class Severity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ComplaintStatus(str, enum.Enum):
    NEW = "NEW"
    PROCESSING = "PROCESSING"
    CLUSTERED = "CLUSTERED"
    INVESTIGATED = "INVESTIGATED"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class ClusterStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    CONFIRMED = "CONFIRMED"
    INVESTIGATING = "INVESTIGATING"
    CASE_CREATED = "CASE_CREATED"
    RESOLVED = "RESOLVED"


class CaseStatus(str, enum.Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    DECISION_READY = "DECISION_READY"
    INTERVENTION_SELECTED = "INTERVENTION_SELECTED"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    MONITORING = "MONITORING"
    CLOSED = "CLOSED"


class EvidenceType(str, enum.Enum):
    COMPLAINT = "COMPLAINT"
    RAINFALL = "RAINFALL"
    TERRAIN = "TERRAIN"
    DRAINAGE = "DRAINAGE"
    ROAD = "ROAD"
    SATELLITE = "SATELLITE"
    FIELD_PHOTO = "FIELD_PHOTO"
    HISTORICAL_INCIDENT = "HISTORICAL_INCIDENT"
    WORK_ORDER = "WORK_ORDER"
    OUTCOME = "OUTCOME"
    CROSS_CITY_CASE = "CROSS_CITY_CASE"
    MODEL_OUTPUT = "MODEL_OUTPUT"
    LAND_COVER = "LAND_COVER"
    INFRASTRUCTURE = "INFRASTRUCTURE"


class HypothesisStatus(str, enum.Enum):
    PROPOSED = "PROPOSED"
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"
    SUPERSEDED = "SUPERSEDED"


class ApprovalState(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class WorkOrderStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TaskStatus(str, enum.Enum):
    PENDING = "PENDING"
    READY = "READY"
    IN_PROGRESS = "IN_PROGRESS"
    BLOCKED = "BLOCKED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    SKIPPED = "SKIPPED"
    ESCALATED = "ESCALATED"


class ExecutionEventType(str, enum.Enum):
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_DELAYED = "TASK_DELAYED"
    RESOURCE_CHANGED = "RESOURCE_CHANGED"
    TASK_BLOCKED = "TASK_BLOCKED"
    PLAN_REVISED = "PLAN_REVISED"
    APPROVAL_GRANTED = "APPROVAL_GRANTED"


class VerificationStatus(str, enum.Enum):
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REJECTED = "REJECTED"


class EvidenceConsistency(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class OutcomeStatus(str, enum.Enum):
    IMPROVED = "IMPROVED"
    UNCHANGED = "UNCHANGED"
    RECURRENCE = "RECURRENCE"
    INCONCLUSIVE = "INCONCLUSIVE"


class PredictionComparison(str, enum.Enum):
    MATCHED = "MATCHED"
    PARTIALLY_MATCHED = "PARTIALLY_MATCHED"
    MISMATCHED = "MISMATCHED"
    INCONCLUSIVE = "INCONCLUSIVE"


class ImportStatus(str, enum.Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    PARTIAL = "PARTIAL"


class FailureType(str, enum.Enum):
    WATERLOGGING = "WATERLOGGING"
    ROAD_DAMAGE = "ROAD_DAMAGE"
    DRAINAGE_FAILURE = "DRAINAGE_FAILURE"
    SEWAGE_OVERFLOW = "SEWAGE_OVERFLOW"
    STRUCTURAL_DAMAGE = "STRUCTURAL_DAMAGE"
    UTILITY_FAILURE = "UTILITY_FAILURE"
    EROSION = "EROSION"
    SUBSIDENCE = "SUBSIDENCE"
    OTHER = "OTHER"
