"""Initial Schema

Revision ID: 61c646e9ca50
Revises: 
Create Date: 2026-10-04 20:24:06.973476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c646e9ca50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_imports',
    sa.Column('import_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('accepted_rows', sa.Integer(), nullable=True),
    sa.Column('rejected_rows', sa.Integer(), nullable=True),
    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('processing_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('import_id')
    )
    op.create_table('reference_cases',
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('problem_type', sa.String(), nullable=False),
    sa.Column('intervention', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('approximate_cost', sa.Float(), nullable=True),
    sa.Column('cost_currency', sa.String(), nullable=True),
    sa.Column('duration_reported', sa.String(), nullable=True),
    sa.Column('reported_outcome', sa.String(), nullable=True),
    sa.Column('recurrence_evidence', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_reference', sa.String(), nullable=True),
    sa.Column('applicability_notes', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('reference_id')
    )
    op.create_table('sites',
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('site_label', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('road_segment_id', sa.String(), nullable=True),
    sa.Column('h3_cell', sa.String(), nullable=True),
    sa.Column('drain_ids', sa.JSON(), nullable=True),
    sa.Column('building_ids', sa.JSON(), nullable=True),
    sa.Column('terrain_elevation', sa.Float(), nullable=True),
    sa.Column('terrain_slope', sa.Float(), nullable=True),
    sa.Column('land_cover', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('failure_clusters',
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('complaint_count', sa.Integer(), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('spatial_radius_m', sa.Float(), nullable=True),
    sa.Column('time_range_start', sa.DateTime(), nullable=True),
    sa.Column('time_range_end', sa.DateTime(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('severity_distribution', sa.JSON(), nullable=True),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('cluster_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('infrastructure_memory',
    sa.Column('memory_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('timeline', sa.JSON(), nullable=True),
    sa.Column('total_complaints', sa.Integer(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('total_interventions', sa.Integer(), nullable=True),
    sa.Column('total_recurrences', sa.Integer(), nullable=True),
    sa.Column('successful_interventions', sa.JSON(), nullable=True),
    sa.Column('failed_interventions', sa.JSON(), nullable=True),
    sa.Column('learned_patterns', sa.JSON(), nullable=True),
    sa.Column('last_incident_at', sa.DateTime(), nullable=True),
    sa.Column('last_intervention_at', sa.DateTime(), nullable=True),
    sa.Column('recurrence_intervals', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_table('complaints',
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('import_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('original_address', sa.String(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('normalized_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['failure_clusters.cluster_id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['csv_imports.import_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index('idx_complaint_cluster', 'complaints', ['cluster_id'], unique=False)
    op.create_index('idx_complaint_location', 'complaints', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_complaint_reported_at', 'complaints', ['reported_at'], unique=False)
    op.create_index('idx_complaint_site', 'complaints', ['site_id'], unique=False)
    op.create_index('idx_complaint_ward', 'complaints', ['ward'], unique=False)
    op.create_table('failure_cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('failure_type', sa.String(), nullable=True),
    sa.Column('recurrence_count', sa.Integer(), nullable=True),
    sa.Column('impact_summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.JSON(), nullable=True),
    sa.Column('failure_chain', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['failure_clusters.cluster_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('failure_hypotheses',
    sa.Column('hypothesis_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('limitations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.PrimaryKeyConstraint('hypothesis_id')
    )
    op.create_table('historical_incidents',
    sa.Column('incident_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('incident_type', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('intervention_taken', sa.String(), nullable=True),
    sa.Column('intervention_outcome', sa.String(), nullable=True),
    sa.Column('recurrence_after_days', sa.Integer(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('intervention_constraints',
    sa.Column('constraint_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('budget_limit', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('available_workers', sa.Integer(), nullable=True),
    sa.Column('available_equipment', sa.JSON(), nullable=True),
    sa.Column('available_materials', sa.JSON(), nullable=True),
    sa.Column('operational_restrictions', sa.JSON(), nullable=True),
    sa.Column('weather_constraints', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_table('intervention_options',
    sa.Column('intervention_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intervention_type', sa.String(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('estimated_duration_days', sa.Float(), nullable=True),
    sa.Column('workers_required', sa.Integer(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('complaints_addressed', sa.Integer(), nullable=True),
    sa.Column('expected_risk_reduction', sa.Float(), nullable=True),
    sa.Column('recurrence_outlook', sa.String(), nullable=True),
    sa.Column('maintenance_burden', sa.String(), nullable=True),
    sa.Column('future_savings', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('budget_fit', sa.Float(), nullable=True),
    sa.Column('deadline_fit', sa.Float(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.PrimaryKeyConstraint('intervention_id')
    )
    op.create_table('decision_analyses',
    sa.Column('analysis_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('constraint_id', sa.String(), nullable=True),
    sa.Column('ranked_interventions', sa.JSON(), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=True),
    sa.Column('cost_of_inaction', sa.JSON(), nullable=True),
    sa.Column('counterfactual', sa.JSON(), nullable=True),
    sa.Column('selected_intervention_id', sa.String(), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.ForeignKeyConstraint(['constraint_id'], ['intervention_constraints.constraint_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_table('predictions',
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('intervention_id', sa.String(), nullable=True),
    sa.Column('predicted_metric', sa.String(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention_options.intervention_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_table('resolution_plans',
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('intervention_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phases', sa.JSON(), nullable=True),
    sa.Column('total_duration_days', sa.Float(), nullable=True),
    sa.Column('total_estimated_cost', sa.Float(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('contingencies', sa.JSON(), nullable=True),
    sa.Column('approval_state', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention_options.intervention_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('work_orders',
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('intervention_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approval_state', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention_options.intervention_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['resolution_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('work_order_id')
    )
    op.create_table('outcome_observations',
    sa.Column('outcome_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('trigger_event', sa.String(), nullable=True),
    sa.Column('trigger_event_details', sa.JSON(), nullable=True),
    sa.Column('observed_conditions', sa.JSON(), nullable=True),
    sa.Column('complaints_during_event', sa.Integer(), nullable=True),
    sa.Column('spatial_impact', sa.JSON(), nullable=True),
    sa.Column('verification_evidence_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    op.create_table('replan_events',
    sa.Column('replan_id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('trigger_event_id', sa.String(), nullable=True),
    sa.Column('previous_plan', sa.JSON(), nullable=True),
    sa.Column('new_plan', sa.JSON(), nullable=True),
    sa.Column('affected_tasks', sa.JSON(), nullable=True),
    sa.Column('deadline_risk', sa.String(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('replan_id')
    )
    op.create_table('verifications',
    sa.Column('verification_id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('overall_consistency', sa.String(), nullable=True),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('manual_review_required', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_table('work_order_tasks',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('planned_duration_hours', sa.Float(), nullable=True),
    sa.Column('actual_duration_hours', sa.Float(), nullable=True),
    sa.Column('workers', sa.JSON(), nullable=True),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delay_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('execution_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['work_order_tasks.task_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('field_evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('work_order_id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('location_consistency', sa.String(), nullable=True),
    sa.Column('timestamp_consistency', sa.String(), nullable=True),
    sa.Column('duplicate_similarity', sa.Float(), nullable=True),
    sa.Column('visual_change', sa.String(), nullable=True),
    sa.Column('manipulation_indicators', sa.JSON(), nullable=True),
    sa.Column('overall_consistency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['work_order_tasks.task_id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.work_order_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('prediction_reality_comparisons',
    sa.Column('comparison_id', sa.String(), nullable=False),
    sa.Column('prediction_id', sa.String(), nullable=False),
    sa.Column('outcome_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('predicted_metric', sa.String(), nullable=False),
    sa.Column('comparison_result', sa.String(), nullable=True),
    sa.Column('error', sa.Float(), nullable=True),
    sa.Column('error_percentage', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('comparison_date', sa.DateTime(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome_observations.outcome_id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('comparison_id')
    )
    op.create_table('learning_records',
    sa.Column('learning_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=True),
    sa.Column('comparison_id', sa.String(), nullable=True),
    sa.Column('learning_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('previous_confidence', sa.Float(), nullable=True),
    sa.Column('updated_confidence', sa.Float(), nullable=True),
    sa.Column('intervention_type', sa.String(), nullable=True),
    sa.Column('effectiveness_rating', sa.Float(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('evidence_ids', sa.JSON(), nullable=True),
    sa.Column('data_truth', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['failure_cases.case_id'], ),
    sa.ForeignKeyConstraint(['comparison_id'], ['prediction_reality_comparisons.comparison_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ),
    sa.PrimaryKeyConstraint('learning_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_records')
    op.drop_table('prediction_reality_comparisons')
    op.drop_table('field_evidence')
    op.drop_table('execution_events')
    op.drop_table('work_order_tasks')
    op.drop_table('verifications')
    op.drop_table('replan_events')
    op.drop_table('outcome_observations')
    op.drop_table('work_orders')
    op.drop_table('resolution_plans')
    op.drop_table('predictions')
    op.drop_table('decision_analyses')
    op.drop_table('intervention_options')
    op.drop_table('intervention_constraints')
    op.drop_table('historical_incidents')
    op.drop_table('failure_hypotheses')
    op.drop_table('evidence')
    op.drop_table('failure_cases')
    op.drop_index('idx_complaint_ward', table_name='complaints')
    op.drop_index('idx_complaint_site', table_name='complaints')
    op.drop_index('idx_complaint_reported_at', table_name='complaints')
    op.drop_index('idx_complaint_location', table_name='complaints')
    op.drop_index('idx_complaint_cluster', table_name='complaints')
    op.drop_table('complaints')
    op.drop_table('infrastructure_memory')
    op.drop_table('failure_clusters')
    op.drop_table('sites')
    op.drop_table('reference_cases')
    op.drop_table('csv_imports')
    # ### end Alembic commands ###
